import { AppBreadCrumbs } from "@/components/organism/AppBreadCrumbs";
import { AppSidebar } from "@/components/organism/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";

export const metadata = {
  title: "Welcome to beaver",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <AppSidebar />

          <main className="p-6 w-full h-full">
            <AppBreadCrumbs />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
